apiVersion: "apiextensions.k8s.io/v1beta1"
kind: "CustomResourceDefinition"
metadata:
  name: "globaldeploymentpolicies.avilb.k8s.io"
spec:
  group: "avilb.k8s.io"
  version: "v1alpha1"
  scope: "Namespaced"
  names:
    plural: "globaldeploymentpolicies"
    singular: "globaldeploymentpolicy"
    kind: "GlobalDeploymentPolicy"
    shortNames:
      - "gdp"
  validation:
    openAPIV3Schema:
      required: ["spec"]
      properties:
        spec:
          properties:
            matchRules:
              type: "array"
              items:
                properties:
                  object:
                    type: "string"
                    enum: [INGRESS, ROUTE, LBSVC]
                  hosts:
                    type: "array"
                    items:
                      properties:
                        host:
                          type: "string"
                  label:
                    properties:
                      key:
                        type: "string"
                      value:
                        type: "string"
                  op:
                    type: "string"
                    enum: [EQUALS, GLOB, NOTEQUALS]
            matchClusters:
              type: "array"
              items:
                properties:
                  clusterContext:
                    type: "string"
            gslbConfig:
              type: "string"
            trafficSplit:
              type: "array"
              items:
                properties:
                  cluster:
                    type: "string"
                  weight:
                    type: integer
            lbAlgorithm:
              type: "string"
