apiVersion: "apiextensions.k8s.io/v1beta1"
kind: "CustomResourceDefinition"
metadata:
  name: "globaldeploymentpolicies.amko.k8s.io"
spec:
  group: "amko.k8s.io"
  version: "v1alpha1"
  scope: "Namespaced"
  names:
    plural: "globaldeploymentpolicies"
    singular: "globaldeploymentpolicy"
    kind: "GlobalDeploymentPolicy"
    shortNames:
      - "gdp"
  validation:
    openAPIV3Schema:
      required: ["spec"]
      properties:
        spec:
          properties:
            matchRules:
              properties:
                appSelector:
                  properties:
                    label:
                      type: "object"
                      additonalPrpoerties:
                        type: "string"
                namespaceSelector:
                  properties:
                    label:
                      type: "object"
                      additonalPrpoerties:
                        type: "string"
            matchClusters:
              type: "array"
              items:
                object:
                  type: "string"
            trafficSplit:
              type: "array"
              items:
                properties:
                  cluster:
                    type: "string"
                  weight:
                    type: integer
