apiVersion: "apiextensions.k8s.io/v1beta1"
kind: "CustomResourceDefinition"
metadata:
  name: "gslbconfigs.amko.k8s.io"
spec:
  group: "amko.k8s.io"
  version: "v1alpha1"
  scope: "Namespaced"
  names:
    plural: "gslbconfigs"
    singular: "gslbconfig"
    kind: "GSLBConfig"
    shortNames:
    - "gc"
  validation:
    openAPIV3Schema:
      required: ["spec"]
      properties:
        spec:
          properties:
            gslbLeader:
              properties:
                credentials:
                  type: "string"
                controllerVersion:
                  type: "string"
                controllerIP:
                  type: "string"
            memberClusters:
              type: "array"
              items:
                properties:
                  clusterContext:
                    type: "string"
            refreshInterval:
              type: "integer"
            logLevel:
              type: "string"
              enum: [DEBUG, INFO, WARN, ERROR]
