apiVersion: "amko.k8s.io/v1alpha1"
kind: "GlobalDeploymentPolicy"
metadata:
  name: "gdp-1"
  namespace: "avi-system"
spec:
  matchRules:
    appSelector:
      label: "app:gslb"
    namespaceSelector:
      label: "ns:gslb"
 
  matchClusters:
    - cluster1
    - cluster2
 
  trafficSplit:
    - cluster: cluster1
      weight: 80
    - cluster: cluster2
      weight: 20
