# permissions for end users to edit amkoclusters.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: amkocluster-editor-role
rules:
- apiGroups:
  - amko.vmware.com.github.com
  resources:
  - amkoclusters
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - amko.vmware.com.github.com
  resources:
  - amkoclusters/status
  verbs:
  - get
