
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - amko.vmware.com.github.com
  resources:
  - amkoclusters
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - amko.vmware.com.github.com
  resources:
  - amkoclusters/finalizers
  verbs:
  - update
- apiGroups:
  - amko.vmware.com.github.com
  resources:
  - amkoclusters/status
  verbs:
  - get
  - patch
  - update
