kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: amko-role
rules:
  - apiGroups: ["extensions", "networking.k8s.io"]
    resources: ["ingresses"]
    verbs: ["get","watch","list"]
  - apiGroups: ["route.openshift.io"]
    resources: ["routes"]
    verbs: ["get","watch","list"]
  - apiGroups: ["route.openshift.io"]
    resources: ["routes"]
    verbs: ["get","watch","list"]
  - apiGroups: [""]
    resources: ["services", "secrets"]
    verbs: ["get", "watch", "list"]
  - apiGroups: ["avilb.k8s.io"]
    resources: ["gslbconfigs", "gslbconfigs/status", "globaldeploymentpolicies", "globaldeploymentpolicies/status"]
    verbs: ["get","watch","list","patch", "update"]
