kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: amko-role
rules:
  - apiGroups: ["extensions", "networking.k8s.io"]
    resources: ["ingresses"]
    verbs: ["get","watch","list"]
  - apiGroups: ["route.openshift.io"]
    resources: ["routes"]
    verbs: ["get","watch","list"]
  - apiGroups: ["route.openshift.io"]
    resources: ["routes"]
    verbs: ["get","watch","list"]
  - apiGroups: [""]
    resources: ["services", "secrets", "namespaces"]
    verbs: ["get", "watch", "list"]
  - apiGroups: ["amko.vmware.com"]
    resources: ["gslbconfigs", "gslbconfigs/status", "globaldeploymentpolicies", "globaldeploymentpolicies/status", "gslbhostrules", "gslbhostrules/status"]
    verbs: ["get","watch","list","patch", "update"]

{{- if .Values.rbac.pspEnable }}
  - apiGroups:
    - policy
    - extensions
    resources:
    - podsecuritypolicies
    verbs:
    - use
    resourceNames:
    - {{ template "amko.name" . }}
{{- end }}