apiVersion: apps/v1
kind: Deployment
metadata:
  name: amko
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "amko.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "amko.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "amko.selectorLabels" . | nindent 8 }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      serviceAccountName: amko-sa
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      {{ if .Values.persistentVolumeClaim }}
      volumes:
      - name: amko-pv-storage
        persistentVolumeClaim:
          claimName: {{ .Values.persistentVolumeClaim }}
      {{ end }}
      containers:
        - name: {{ .Chart.Name }}
          {{ if .Values.persistentVolumeClaim }}
          volumeMounts:
          - mountPath: {{ .Values.mountPath }}
            name: amko-pv-storage
          {{ end }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Chart.AppVersion }}"
          env:
          - name: GSLB_CONFIG
            valueFrom:
              secretKeyRef:
                name: {{ .Values.configs.clusterMembers.secret }}
                key: {{ .Values.configs.clusterMembers.key }}
          {{ if .Values.persistentVolumeClaim }}
          - name: USE_PVC
            value: "true"
          {{ end }}
          - name: LOG_FILE_NAME
            value: {{ printf "%s/%s" .Values.mountPath .Values.logFile }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
