apiVersion: "amko.vmware.com/v1alpha2"
kind: "GlobalDeploymentPolicy"
metadata:
  name: "global-gdp"
  namespace: "avi-system"
spec:
  matchRules:
{{- with .Values.globalDeploymentPolicy.appSelector }}
    appSelector:
  {{- toYaml . | nindent 6 }}
{{- end }}
{{- with .Values.globalDeploymentPolicy.namespaceSelector }}
    namespaceSelector:
  {{- toYaml . | nindent 6 }}
{{- end }}
{{- with .Values.globalDeploymentPolicy.matchClusters }}
  matchClusters:
  {{- toYaml . | nindent 4 }}
{{- end }}
{{- with .Values.globalDeploymentPolicy.trafficSplit }}
  trafficSplit:
  {{- toYaml . | nindent 4 }}
{{- end }}
{{- with .Values.globalDeploymentPolicy.ttl }}
  ttl: {{ .Values.globalDeploymentPolicy.ttl }}
{{- end }}
