apiVersion: "amko.k8s.io/v1alpha1"
kind: "GlobalDeploymentPolicy"
metadata:
  name: "global-gdp"
  namespace: "avi-system"
spec:
  matchRules:
    appSelector:
{{- with .Values.globalDeploymentPolicy.appSelector }}
      {{- toYaml . | nindent 6 }}
{{- end }}
    namespaceSelector:
{{- with .Values.globalDeploymentPolicy.namespaceSelector }}
      {{- toYaml . | nindent 6 }}
  {{- end }}
  matchClusters:
{{- with .Values.globalDeploymentPolicy.matchClusters }}
    {{- toYaml . | nindent 4 }}
{{- end }}
{{- with .Values.globalDeploymentPolicy.trafficSplit }}
  trafficSplit:
  {{- toYaml . | nindent 4 }}
{{- end }}
