apiVersion: "amko.k8s.io/v1alpha1"
kind: "GSLBConfig"
metadata:
  name: "gc-1"
  namespace: {{ .Release.Namespace }}
spec:
  gslbLeader:
    credentials: "gslb-avi-secret"
    controllerVersion: {{ .Values.configs.controllerVersion }}
    controllerIP: {{ .Values.configs.gslbLeaderController }}
{{- with .Values.configs.memberClusters }}
  memberClusters:
    {{- toYaml . | nindent 4 }}
{{- end }}
  refreshInterval: {{ .Values.configs.refreshInterval }}
  logLevel: {{ .Values.configs.logLevel }}